### ISSUE TITLE
when building the master it shows an error and on the newest release

### ISSUE THREAD

**Issue by Meowzer2005** [Chadderz121/brainslug-wii#5]
$ make
Compiling from Windows_NT
DEVKITPRO corrected to opt:/devkitpro
DEVKITPPC corrected to opt:/devkitpro/devkitPPC
build/src/modules/module.c.d
/bin/sh: powerpc-eabi-g++: command not found
Makefile:196: build/src/modules/module.c.d: No such file or directory
make: *** [Makefile:240: build/src/modules/module.c.d] Error 1
i get that error when on master and a for the latest release that's basically the same but with libelf_shdr.c.d

**Comment by Leseratte10** [comment]
That looks like your environment variables for DEVKITPRO and DEVKITPPC are set wrong. Can you check what these are set to?

**Comment by Meowzer2005** [comment]
fixed this a while ago sorry

**Comment by JohnTitour** [comment]
How did you figured out how to resolve your problem ? I face the same issue and I don't find any solution.
Also, my DEVKITPRO and DEVKITPPC environment variables seems to be set correctly ; until this step in the make process I don't have any error.

![image](https://github.com/user-attachments/assets/3f90788e-aba2-49e1-a07a-e3df076fcde1)
![image](https://github.com/user-attachments/assets/408f0a1c-07f7-4e07-b96d-60a37b26d052)

On MacOS and Windows I face the same issue.

**Comment by JohnTitour** [comment]
I also figured out what was wrong, the devkitPRO/devkitPPC/bin folder wasn't set in the PATH env variable as it should have been.
